// Mocks generated by Mockito 5.4.4 from annotations
// in huggi_patient_app/test/integration/appointment_notifications_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:huggi_patient_app/core/notifications/email_notification_service.dart'
    as _i13;
import 'package:huggi_patient_app/core/notifications/local_notification_service.dart'
    as _i11;
import 'package:huggi_patient_app/core/notifications/whatsapp_notification_service.dart'
    as _i12;
import 'package:huggi_patient_app/core/storage/hive_cache_service.dart' as _i7;
import 'package:huggi_patient_app/features/appointments/data/models/appointment_model.dart'
    as _i8;
import 'package:huggi_patient_app/features/appointments/domain/entities/appointment_entity.dart'
    as _i4;
import 'package:huggi_patient_app/features/appointments/domain/usecases/cancel_appointment_usecase.dart'
    as _i5;
import 'package:huggi_patient_app/features/appointments/domain/usecases/get_my_appointments_usecase.dart'
    as _i2;
import 'package:huggi_patient_app/features/appointments/domain/usecases/reschedule_appointment_usecase.dart'
    as _i6;
import 'package:huggi_patient_app/features/auth/data/models/patient_model.dart'
    as _i10;
import 'package:huggi_patient_app/features/queue/data/models/queue_position_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetMyAppointmentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMyAppointmentsUseCase extends _i1.Mock
    implements _i2.GetMyAppointmentsUseCase {
  MockGetMyAppointmentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.AppointmentEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AppointmentEntity>>.value(
            <_i4.AppointmentEntity>[]),
      ) as _i3.Future<List<_i4.AppointmentEntity>>);
}

/// A class which mocks [CancelAppointmentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelAppointmentUseCase extends _i1.Mock
    implements _i5.CancelAppointmentUseCase {
  MockCancelAppointmentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? appointmentId) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [appointmentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RescheduleAppointmentUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRescheduleAppointmentUseCase extends _i1.Mock
    implements _i6.RescheduleAppointmentUseCase {
  MockRescheduleAppointmentUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(
    String? appointmentId,
    DateTime? newTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            appointmentId,
            newTime,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [HiveCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveCacheService extends _i1.Mock implements _i7.HiveCacheService {
  MockHiveCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheAppointments(
          List<_i8.AppointmentModel>? appointments) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAppointments,
          [appointments],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.AppointmentModel>?> getAppointments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointments,
          [],
        ),
        returnValue: _i3.Future<List<_i8.AppointmentModel>?>.value(),
      ) as _i3.Future<List<_i8.AppointmentModel>?>);

  @override
  _i3.Future<void> clearAppointments() => (super.noSuchMethod(
        Invocation.method(
          #clearAppointments,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cacheQueuePosition(_i9.QueuePositionModel? queuePosition) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheQueuePosition,
          [queuePosition],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.QueuePositionModel?> getQueuePosition() => (super.noSuchMethod(
        Invocation.method(
          #getQueuePosition,
          [],
        ),
        returnValue: _i3.Future<_i9.QueuePositionModel?>.value(),
      ) as _i3.Future<_i9.QueuePositionModel?>);

  @override
  _i3.Future<void> clearQueuePosition() => (super.noSuchMethod(
        Invocation.method(
          #clearQueuePosition,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cachePatientProfile(_i10.PatientModel? patient) =>
      (super.noSuchMethod(
        Invocation.method(
          #cachePatientProfile,
          [patient],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i10.PatientModel?> getPatientProfile() => (super.noSuchMethod(
        Invocation.method(
          #getPatientProfile,
          [],
        ),
        returnValue: _i3.Future<_i10.PatientModel?>.value(),
      ) as _i3.Future<_i10.PatientModel?>);

  @override
  _i3.Future<void> clearPatientProfile() => (super.noSuchMethod(
        Invocation.method(
          #clearPatientProfile,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock
    implements _i11.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleAppointmentReminders(
          _i4.AppointmentEntity? appointment) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleAppointmentReminders,
          [appointment],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelReminder(String? appointmentId) => (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [appointmentId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllReminders,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [WhatsAppNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWhatsAppNotificationService extends _i1.Mock
    implements _i12.WhatsAppNotificationService {
  MockWhatsAppNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendAppointmentConfirmation(
    _i4.AppointmentEntity? appointment,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAppointmentConfirmation,
          [
            appointment,
            phoneNumber,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendAppointmentReminder(
    _i4.AppointmentEntity? appointment,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAppointmentReminder,
          [
            appointment,
            phoneNumber,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendCancellationConfirmation(
    _i4.AppointmentEntity? appointment,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCancellationConfirmation,
          [
            appointment,
            phoneNumber,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendRescheduleConfirmation(
    _i4.AppointmentEntity? appointment,
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRescheduleConfirmation,
          [
            appointment,
            phoneNumber,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [EmailNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailNotificationService extends _i1.Mock
    implements _i13.EmailNotificationService {
  MockEmailNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> sendAppointmentConfirmation(
    _i4.AppointmentEntity? appointment,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAppointmentConfirmation,
          [
            appointment,
            email,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendAppointmentReminder(
    _i4.AppointmentEntity? appointment,
    String? email, {
    required bool? isUrgent,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendAppointmentReminder,
          [
            appointment,
            email,
          ],
          {#isUrgent: isUrgent},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendCancellationConfirmation(
    _i4.AppointmentEntity? appointment,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCancellationConfirmation,
          [
            appointment,
            email,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> sendRescheduleConfirmation(
    _i4.AppointmentEntity? appointment,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRescheduleConfirmation,
          [
            appointment,
            email,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
